### PR TITLE
Create To-Do Items complete

### PR DESCRIPTION
**Pull request by camille-seguette**
It's saying I can't automatically merge for some reason, but can make a pull request...

### CODE REVIEW

**Comment by brittanyjspringer** [comment]
@camille-seguette can you walk through the instructions above to fix the conflicts? Looks like Master wasn't updated on your Items branch.

**Comment by camille-seguette** [comment]
Ugh, so I attempted to do this from the command line, but apparently something screwed up along the way... This is my command line history:

Camilles-MacBook-Pro:checkitoff camille$ git checkout create-to-do-items
```Switched to branch 'create-to-do-items'
Camilles-MacBook-Pro:checkitoff camille$ git fetch origin
```remote: Counting objects: 1, done.
```remote: Total 1 (delta 0), reused 0 (delta 0), pack-reused 1
```Unpacking objects: 100% (1/1), done.
```From https://github.com/camille-seguette/checkitoff
   32ef5c2..19760f0  master     -> origin/master
Camilles-MacBook-Pro:checkitoff camille$ git checkout -b create-to-do-items origin/create-to-do-```items
```fatal: A branch named 'create-to-do-items' already exists.
Camilles-MacBook-Pro:checkitoff camille$ git merge master
```Already up-to-date.
Camilles-MacBook-Pro:checkitoff camille$ git checkout master
```Switched to branch 'master'
```Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
```  (use "git pull" to update your local branch)
Camilles-MacBook-Pro:checkitoff camille$ git pull
```Updating 32ef5c2..19760f0
```Fast-forward
``` app/assets/javascripts/welcome.coffee     |   3 -
``` app/assets/stylesheets/welcome.scss       |   3 -
``` app/controllers/application_controller.rb |   4 +
``` app/controllers/users_controller.rb       |   5 +
``` app/helpers/users_helper.rb               |   2 +
``` app/views/layouts/application.html.erb    |  24 ++-
``` app/views/users/show.html.erb             |   1 +
``` config/routes.rb                          |   2 +
``` coverage/.last_run.json                   |   2 +-
``` coverage/.resultset.json                  |  83 ++++++++-
``` coverage/index.html                       | 654 ```++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------
``` spec/controllers/users_controller_spec.rb |  26 +++
``` spec/factories/users.rb                   |   7 +
``` 13 files changed, 719 insertions(+), 97 deletions(-)
``` delete mode 100644 app/assets/javascripts/welcome.coffee
``` delete mode 100644 app/assets/stylesheets/welcome.scss
``` create mode 100644 app/controllers/users_controller.rb
``` create mode 100644 app/helpers/users_helper.rb
``` create mode 100644 app/views/users/show.html.erb
``` create mode 100644 spec/controllers/users_controller_spec.rb
``` create mode 100644 spec/factories/users.rb
Camilles-MacBook-Pro:checkitoff camille$ git status
```On branch master
```Your branch is up-to-date with 'origin/master'.
```nothing to commit, working directory clean
Camilles-MacBook-Pro:checkitoff camille$ git status
```On branch master
```Your branch is up-to-date with 'origin/master'.
```nothing to commit, working directory clean
Camilles-MacBook-Pro:checkitoff camille$ git checkout master
```Already on 'master'
```Your branch is up-to-date with 'origin/master'.
Camilles-MacBook-Pro:checkitoff camille$ git merge --no-ff create-to-do-items
```Auto-merging coverage/index.html
```CONFLICT (content): Merge conflict in coverage/index.html
```Auto-merging coverage/.resultset.json
```CONFLICT (content): Merge conflict in coverage/.resultset.json
```Auto-merging coverage/.last_run.json
```CONFLICT (content): Merge conflict in coverage/.last_run.json
```Auto-merging config/routes.rb
```Auto-merging app/views/users/show.html.erb
```CONFLICT (add/add): Merge conflict in app/views/users/show.html.erb
```Auto-merging app/views/layouts/application.html.erb
```Auto-merging app/controllers/users_controller.rb
```CONFLICT (add/add): Merge conflict in app/controllers/users_controller.rb
```Automatic merge failed; fix conflicts and then commit the result.


:/

**Comment by brittanyjspringer** [comment]
@camille-seguette no worries! What I did was clone the repo, pull down master, create the items branch and then pulled items down. You had two files that were causing the issues. Tests are passing so I'll go ahead and merge. Please be sure to checkout to Master locally and pull down before checking out again. 👍

**Comment by camille-seguette** [comment]
Okay, I don't get why I'm getting this on my terminal:

Camilles-MacBook-Pro:checkitoff camille$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
You have unmerged paths.
  (fix conflicts and run "git commit")

Changes to be committed:

	new file:   app/controllers/items_controller.rb
	new file:   app/helpers/items_helper.rb
	new file:   app/models/item.rb
	modified:   app/models/user.rb
	new file:   app/views/items/_form.html.erb
	new file:   app/views/items/_item.html.erb
	modified:   app/views/layouts/application.html.erb
	modified:   config/routes.rb
	new file:   db/migrate/20170111233322_create_items.rb
	modified:   db/schema.rb
	new file:   spec/controllers/items_controller.rb
	new file:   spec/factories/item.rb
	new file:   spec/factories/user.rb
	new file:   spec/models/item_spec.rb
	new file:   spec/models/user_spec.rb
	modified:   spec/rails_helper.rb

Unmerged paths:
  (use "git add <file>..." to mark resolution)

	both added:      app/controllers/users_controller.rb
	both added:      app/views/users/show.html.erb
	both modified:   coverage/.last_run.json
	both modified:   coverage/.resultset.json
	both modified:   coverage/index.html

Camilles-MacBook-Pro:checkitoff camille$ git checkout master
app/controllers/users_controller.rb: needs merge
app/views/users/show.html.erb: needs merge
coverage/.last_run.json: needs merge
coverage/.resultset.json: needs merge
coverage/index.html: needs merge
error: you need to resolve your current index first
Camilles-MacBook-Pro:checkitoff camille$

**Comment by brittanyjspringer** [comment]
Solved by removing the repository locally and re-cloning it down. Confirmed that you are good to go for the next checkpoint!

**Pull request merged**
